# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote/*

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '56d0d0ed-5b7e-4e72-8d37-a148fa59c4ac'
  imageRepository: 'votingapp'
  containerRegistry: 'jasazurecicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: Build
      displayName: Build an image
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: '$(dockerRegistryServiceConnection)'
            repository: '$(imageRepository)'
            command: 'build'
            Dockerfile: '$(dockerfilePath)'
            tags: |
              $(tag)

- stage: Push
  displayName: Push
  jobs:
    - job: Push
      displayName: Push an image
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: '$(dockerRegistryServiceConnection)'
            repository: '$(imageRepository)'
            command: 'push'
            tags: |
              $(tag)

